podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      imagePullSecrets:
      - name: regcred    
      containers:
      - name: k8s-utilities
        image: docker-registry.localdomain:80/devops/k8s-utilities:v0.1
        command:
        - sleep
        args:
        - 9999999      
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - sleep
        args:
        - 9999999
        volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
      restartPolicy: Never
      volumes:
      - name: kaniko-secret
        secret:
            secretName: regcred
            items:
            - key: .dockerconfigjson
              path: config.json
''') 

{
  node(POD_LABEL) {

    container('k8s-utilities') {
      stage('Deploy image via k8s-utilities') {
            
        dir(path: './blue-green-app/deploy/helm-charts') {
          withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
              sh '''
                pwd && ls -l && \
                helm list -n default --kubeconfig=$KUBECONFIG && \
                kubectl get pods --kubeconfig=$KUBECONFIG
              '''
          }
        }

      }
    }


  }
}
