---
# defaults file for docker

# - containerd.io-1.2.10
# - docker-ce-19.03.4
# - docker-ce-cli-19.03.4

containerd_io_version: 1.6.4
docker_ce_version: 20.10.16

# Docker daemon options as a dict
docker_daemon_options: |
  {
    "exec-opts": ["native.cgroupdriver=systemd"],
    "log-driver": "json-file",
    "log-opts": {
      "max-size": "100m"
    },
    "storage-driver": "overlay2",
    "storage-opts": [
      "overlay2.override_kernel_check=true"
    ],
    "insecure-registries" : ["docker-registry.localdomain:80"]
  }

