apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-server-metrics-servicemonitor
  labels:
    # app: api-server
    app.kubernetes.io/name: api-server
    release: prometheus-monitoring
  namespace: default
spec:
  # jobLabel: myCounter
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
  selector:
    matchLabels:
      # app: api-server
      app.kubernetes.io/name: api-server
      # release: prometheus-monitoring
  namespaceSelector:
    matchNames:
      - default