{
 "title": "API response dashboard",
 "description": "API response dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Response rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(response_status{container=\"api-server\"}[2m]))",
     "legendFormat": "api-server"
    }
   ]
  },
  {
   "title": "Response rate by POD",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(response_status{container=\"api-server\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Response rate green",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(response_status{container=\"api-server\", status=\"green\"}[2m]))",
     "legendFormat": "api-server"
    }
   ]
  },
  {
   "title": "WhatColor POD response delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(http_response_time_seconds_sum[2m])",
     "legendFormat": "{{path}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Response rate blue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(response_status{container=\"api-server\", status=\"blue\"}[2m]))",
     "legendFormat": "api-server"
    }
   ]
  }
 ]
}