apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-server
  namespace: argocd
spec:
  destination:
    namespace: my-test-argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: blue-green-app/deploy/helm-charts/api-server/
    repoURL: 'https://github.com/araskevich/demo-iac.git'
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true