---
# tasks file for docker

- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install required packages
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Install Docker CE
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - containerd.io-{{ containerd_io_version }}
    - docker-ce-{{ docker_ce_version }}
    - docker-ce-{{ docker_ce_version }}

- name: Ensure /etc/docker/ directory exists
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_options | from_json | length > 0

- name: Ensure /etc/systemd/system/docker.service.d directory exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0775
  when: docker_daemon_options | from_json | length > 0

- name: Configure Docker daemon options
  copy:
    content: "{{ docker_daemon_options | from_json | to_nice_json}}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_daemon_options | from_json | length > 0
  notify: Restart service Docker and perform daemon reload

- name: Make sure a Docker service unit is running/enable/not masked (stronger version of disable)
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
    masked: no

